spring:
  config:
    activate.on-profile: local
  zipkin:
    enabled: false
    base-url: "http://localhost:9411"
    sender:
      type: web
  sleuth:
    enabled: false
    sampler:
      probability: 1.0

server:
  port: 9011


