image:
  name: vlaamseoverheid-magda-docker-public.jfrog.io/magda/magda-base-pipeline:jdk21-latest
  username: $ARTIFACTORY_USER
  password: $ARTIFACTORY_PASSWORD

definitions:
  steps:
    - step: &deploy
        name: Deploy to ...
        deployment: PLACEHOLDER
        caches:
          - maven
        script:
          - export INFRA_REPO='magdamock.service-infra'
          - export IFS=' '
          # Allow overwriting applications in deployments
          - >
            if [[ "$APPS" == "" ]]; then
              export APPS='magdamock-service'
            fi
          - echo $NAMESPACE > target/namespace  # Necessary for passing namespace to the next steps
          - chmod +x deploy-with-argocd.sh
          - ./deploy-with-argocd.sh
        artifacts:
          - target/namespace
    - step: &build
        name: Building
        caches:
          - maven
        script:
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - export MAVEN_OPTS="-Xmx1024m"
          - mvn -B -U clean verify -s .m2/settings.xml
        artifacts:
          - "**/*.jar"
    - step: &release
        name: Release
        caches:
          - maven
        script:
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - /bin/bash ./release-application.sh
    - step: &dockerRebuildFromTag
        name: Rebuild Docker from tag
        caches:
          - maven
          - docker
        script:
          - export VERSION=$rebuild_git_tag
          # Checkout
          - source "commons.sh"
          - prepare_git
          - git checkout $VERSION
          - mvn -B package io.fabric8:docker-maven-plugin:0.31.0:push -s .m2/settings.xml -Pdocker-release
    - step: &newmanTest
        name: Newman integration test
        image: postman/newman
        script:
          - export NAMESPACE=`cat target/namespace`
          # No need to proceed if there is no test config found
          - >
            if [[ ! -d "newman-test/" ]]; then
              echo "No newman-test dir found, so not running Postman tests."
              exit 0
            fi
          - npm install -g newman-reporter-junit5
          - apk add curl jq
          - sh ./wait-for-deploy.sh
          - newman run $POSTMAN_URL -e newman-test/$NAMESPACE-config.json -r junit5,cli --reporter-junit5-export test-results/newman-test-results.xml
    - step: &sigridPublish
        image: softwareimprovementgroup/sigridci
        name: Publish to Sigrid
        script:
          - timeout 10m sigridci.py --customer $SIGRID_CI_ACCOUNT --system "Solid" --subsystem $(echo "magdamock.service"| sed -e "s/\./-/g") --source . --publish --include-history
    - step: &dependencyTree
        name: Dependency tree
        caches:
            - maven
        script:
            - mvn dependency:tree > maven.tree
    - step: &sigridCI
        image: softwareimprovementgroup/sigridci
        name: Sigrid CI
        script:
          - timeout 10m sigridci.py --customer $SIGRID_CI_ACCOUNT --system "Solid" --subsystem $(echo "magdamock.service"| sed -e "s/\./-/g") --source .
    - step: &githubMirror
        name: Sync to Github
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:vlaamseoverheid/magdamock.service.git
          - cd magdamock.service.git
          - git push --mirror git@github.com:Informatievlaanderen/MAGDA-Mock.git
clone:
  depth: full

pipelines:
  branches:
    master:
      - parallel:
          steps:
            - step:
                name: Check
                caches:
                  - maven
                script:
                  # Only run for released version
                  - mvn -B -s .m2/settings.xml org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce -Drules=requireReleaseVersion
                  - mkdir -p target
                  - mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout > target/pom_version
                artifacts:
                  - target/pom_version
            - step:
                <<: *dependencyTree
            - step:
                <<: *sigridPublish
      - step:
          <<: *deploy
          name: Deploy release to TST
          deployment: TST_SOLID
      - step:
          <<: *newmanTest
          name: Verify deploy to TST
      - step:
          <<: *deploy
          name: Deploy release to TNI
          deployment: TNI_SOLID
      - step:
          <<: *newmanTest
          name: Verify deploy to TNI
      - step:
          <<: *deploy
          name: Deploy release to PRD
          trigger: manual
          deployment: PRD_SOLID
    develop:
      - parallel:
          steps:
            - step:
                name: Maven
                caches:
                  - maven
                  - docker
                script:
                  - export TESTCONTAINERS_RYUK_DISABLED=true
                  - export MAVEN_OPTS="-Xmx1024m"
                  - mvn -B -U clean deploy sonar:sonar -s .m2/settings.xml -Dbuild=bitbucket  -Pdocker -Dsonar.host.url=${SONAR_HOST} -Dsonar.projectKey=${SONAR_PROJECT} -Dsonar.login=${SONAR_USERNAME} -Dsonar.password=${SONAR_PASSWORD}
                  - mkdir -p target
                  - mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout > target/pom_version
                artifacts:
                  - "**/*.jar"
                  - target/pom_version
            - step:
                <<: *dependencyTree
            - step:
                <<: *sigridPublish
      - step:
          <<: *deploy
          name: Deploy to BETA
          deployment: DEV_SOLID
      - step:
          <<: *newmanTest
          name: Verify deploy to BETA

    hotfix/*:
      - step:
          name: Maven
          caches:
            - maven
            - docker
          script:
            - export TESTCONTAINERS_RYUK_DISABLED=true
            - export MAVEN_OPTS="-Xmx1024m"
            - mvn -B -U clean deploy sonar:sonar -s .m2/settings.xml -Dbuild=bitbucket  -Pdocker -Dsonar.host.url=${SONAR_HOST} -Dsonar.projectKey=${SONAR_PROJECT} -Dsonar.login=${SONAR_USERNAME} -Dsonar.password=${SONAR_PASSWORD} -Dsonar.branch.target=master -Dsonar.branch.name="$BITBUCKET_BRANCH"
            - mkdir -p target
            - mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout > target/pom_version
          artifacts:
            - "**/*.jar"
            - target/pom_version
      - step:
          <<: *deploy
          name: Deploy to BETA
          deployment: DEV_SOLID
      - step:
          <<: *newmanTest
          name: Verify deploy to BETA
      - step:
          <<: *deploy
          name: Deploy to TST
          deployment: TST_SOLID
      - step:
          <<: *newmanTest
          name: Verify deploy to TST
  pull-requests:
    '**':
      - parallel:
          steps:
            - step:
                name: Maven
                caches:
                  - maven
                script:
                  - export TESTCONTAINERS_RYUK_DISABLED=true
                  - export MAVEN_OPTS="-Xmx1024m"
                  - mvn -B -U clean verify sonar:sonar -s .m2/settings.xml -Dbuild=bitbucket  -Dsonar.host.url=${SONAR_HOST} -Dsonar.projectKey=${SONAR_PROJECT} -Dsonar.login=${SONAR_USERNAME} -Dsonar.password=${SONAR_PASSWORD} -Dsonar.branch.name="$BITBUCKET_BRANCH"
                artifacts:
                  - "**/*.jar"
            - step:
                <<: *dependencyTree
            - step:
                <<: *sigridCI
  custom:
    update-dependencies:
      - step:
          name: Dependencies
          caches:
            - maven
          script:
            - apt-get update
            - apt-get install git -y
            - git --version
            - export TESTCONTAINERS_RYUK_DISABLED=true
            - export MAVEN_OPTS="-Xmx1024m"
            # Disabled update-parent till they implement includes parameter like the other update plugins.
            # - mvn versions:update-parent "-DparentVersion=(,2.0)" -B -s .m2/settings.xml
            - mvn versions:update-properties -DallowMajorUpdates=false -Dincludes=be.vlaanderen*:* -B -s .m2/settings.xml
            - mvn versions:use-releases -Dincludes=be.vlaanderen*:* -B -s .m2/settings.xml
            - mvn versions:use-latest-versions -DallowMajorUpdates=false -Dincludes=be.vlaanderen*:* -B -s .m2/settings.xml
            - mvn versions:commit
            - mvn -B -U clean deploy -s .m2/settings.xml -Dbuild=bitbucket  -Pdocker
            - git diff-index --quiet HEAD || git commit -a -m'Bitbucket automated update of released dependencies'
            - git push
          after-script:
            - chmod +x scheduler-slack-publisher.sh
            - ./scheduler-slack-publisher.sh 'update-dependencies'
    create-hotfix:
      - variables:
          - name: starting_branch_of_hotfix
      - step:
          name: Creating hotfix branch
          caches:
            - maven
          script:
            - export TESTCONTAINERS_RYUK_DISABLED=true
            - chmod +x create-hotfix.sh
            - ./create-hotfix.sh
    finish-hotfix:
      - variables:
          - name: skipMergeDev
      - step:
          name: Finishing hotfix
          caches:
            - maven
          script:
            - export TESTCONTAINERS_RYUK_DISABLED=true
            - chmod +x finish-hotfix.sh
            - ./finish-hotfix.sh
    create-support:
      - variables:
          - name: starting_tag
      - step:
          name: Creating support branch
          caches:
            - maven
          script:
            - export TESTCONTAINERS_RYUK_DISABLED=true
            - chmod +x create-support.sh
            - ./create-support.sh
    maven-release:
      - step: *release
      - step: *githubMirror
    deploy-released-version:
      - step:
          name: Check
          caches:
            - maven
          script:
            # Only run for released version
            - mvn -B -s .m2/settings.xml org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce -Drules=requireReleaseVersion
            - mkdir -p target
            - mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout > target/pom_version
          artifacts:
            - target/pom_version
      - step:
          <<: *deploy
          name: Deploy release to TST
          deployment: TST_SOLID
      - step:
          <<: *newmanTest
          name: Verify release to TST
      - step:
          <<: *deploy
          name: Deploy release to TNI
          deployment: TNI_SOLID
      - step:
          <<: *newmanTest
          name: Verify release to TNI
      - step:
          <<: *deploy
          name: Deploy release to PRD
          trigger: manual
          deployment: PRD_SOLID
    owasp-dependencies-check:
      - step:
          name: Owasp Dependencies Check
          caches:
            - maven
          script:
            - export MAVEN_OPTS="-Xmx1024m"
            - mvn -B org.owasp:dependency-check-maven:7.4.4:aggregate -DskipSystemScope=true "-DsuppressionFile=.owasp/owasp-suppression.xml" "-DhintsFile=.owasp/owasp-hints.xml" -DfailBuildOnCVSS=7 -s .m2/settings.xml
          artifacts:
            - target/dependency-check-report.html
          after-script:
            - chmod +x scheduler-slack-publisher.sh
            - ./scheduler-slack-publisher.sh 'owasp-dependency-check'
            - curl -X PUT -u $ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD -T target/dependency-check-report.html "https://vlaamseoverheid.jfrog.io/vlaamseoverheid/magda-owasp/${BITBUCKET_REPO_SLUG}/${BITBUCKET_REPO_SLUG}-${BITBUCKET_BUILD_NUMBER}-$(date +%Y%m%d).html"
    stable-develop-check:
      - step:
          <<: *build
          after-script:
            - chmod +x scheduler-slack-publisher.sh
            - ./scheduler-slack-publisher.sh 'stable-develop-check'
    rebuild-docker-from-tag:
      - variables:
          - name: rebuild_git_tag
      - step: *dockerRebuildFromTag
options:
  docker: true
  size: 2x
