metadata:
  labels:
    version: "${VERSION}"
spec:
  template:
    metadata:
      labels:
        version: "${VERSION}"
      annotations:
        pipeline-deployment: "${DEPLOYMENT_DATE}"
    spec:
      containers:
        - name: "${APP_NAME}"
          image: vlaamseoverheid-magda-docker-public.jfrog.io/magda/${APP_IMAGE}:${VERSION}
