FROM vlaamseoverheid-magda-docker-public.jfrog.io/magda/vdip-java:${vdip-java.version}

VOLUME /tmp
# The docker image expects this location
COPY target/${project.build.finalName}.jar /opt/app/app.jar
# The helm chart expects this location
COPY target/${project.build.finalName}.jar /app.jar

EXPOSE 8080:8080
