name: publish-javadoc
run-name: Publish Javadocs to Github pages
on:
  push:
  release:
    types: [created]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  generate-javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: javadoc-cache
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Generate JavaDoc
        run: mvn --batch-mode install javadoc:javadoc
      - name: Upload interface artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: interfaces/target/reports/apidocs
          
  deploy:
    needs: generate-javadoc
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
