# Publish JAR and docker image to Github packages
name: publish-artifacts
run-name: Publish artifacts to Github packages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: mvn-cache
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package -pl "!tester"
  
  publish-jar:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: mvn-cache
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Publish
        run: mvn --batch-mode deploy -pl "!tester" -P "!artifactory,github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
